// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1.Models;

namespace Task1.Migrations
{
    [DbContext(typeof(DoctorsContext))]
    [Migration("20201103035812_add-desc-to-DoctorInfo")]
    partial class adddesctoDoctorInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task1.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Desc");

                    b.Property<string>("Family");

                    b.Property<byte[]>("Image")
                        .HasColumnType("image");

                    b.Property<DateTimeOffset>("MyProperty");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OfficeImage");

                    b.Property<int>("Row")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("DoctorID");

                    b.ToTable("DoctorsInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
